[package]
name = "moontide-protocol"
description = "MoonTide LLM protocol and Session log types"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
