export const COMPACT_KEEP_TURNS_DEFAULT = 3;
export const COMPACT_THRESHOLD_DEFAULT = 85;
export const ARTIFACT_SPILL_THRESHOLD_BYTES_DEFAULT = 8192;
export const CODE_REPL_DEFAULT_RUNTIME = "tsx";
export const CODE_REPL_TIMEOUT_MS_DEFAULT = 120_000;
export const TRACE_PREVIEW_CHARS_DEFAULT = 120;
