import { PRODUCT_SLUG } from "./brand.js";

/** Prefix for MoonTide-specific environment variables. */
export const ENV_PREFIX = `${PRODUCT_SLUG.toUpperCase()}_` as const;

/** MoonTide-scoped env keys (without prefix). */
export const APP_ENV = {
  WORKDIR: "WORKDIR",
  CONTEXT_LIMIT: "CONTEXT_LIMIT",
  CONTEXT_EXACT: "CONTEXT_EXACT",
  COMPACT_KEEP_TURNS: "COMPACT_KEEP_TURNS",
  COMPACT_THRESHOLD: "COMPACT_THRESHOLD",
  COMPACT_AUTO: "COMPACT_AUTO",
  ARTIFACT_SPILL_THRESHOLD_BYTES: "ARTIFACT_SPILL_THRESHOLD_BYTES",
  CODE_REPL_DEFAULT_RUNTIME: "CODE_REPL_DEFAULT_RUNTIME",
  CODE_REPL_TIMEOUT_MS: "CODE_REPL_TIMEOUT_MS",
  CODE_REPL_DISABLED: "CODE_REPL_DISABLED",
  PYTHON: "PYTHON",
  VENV: "VENV",
  DEEP_RESEARCH: "DEEP_RESEARCH",
  TAVILY_API_KEY: "TAVILY_API_KEY",
  THINKING: "THINKING",
  VERBOSE: "VERBOSE",
  TRACE_PREVIEW_CHARS: "TRACE_PREVIEW_CHARS",
  LANG: "LANG",
  DEBUG: "DEBUG",
  HTTP: "HTTP",
  ALWAYS_ALLOW: "ALWAYS_ALLOW",
  SIDECAR_PLUGIN_ID: "SIDECAR_PLUGIN_ID",
} as const;

/** Full env var name, e.g. `${ENV_PREFIX}LANG`. */
export function envVarName(key: keyof typeof APP_ENV | string): string {
  return `${ENV_PREFIX}${key}`;
}

/** Provider / third-party env var names. */
export const PROVIDER_ENV = {
  DEEPSEEK_API_KEY: "DEEPSEEK_API_KEY",
  ANTHROPIC_API_KEY: "ANTHROPIC_API_KEY",
  ANTHROPIC_BASE_URL: "ANTHROPIC_BASE_URL",
  ANTHROPIC_AUTH_TOKEN: "ANTHROPIC_AUTH_TOKEN",
  MODEL_ID: "MODEL_ID",
  TAVILY_API_KEY: "TAVILY_API_KEY",
} as const;
