/** Prefix for Ocula-specific environment variables. */
export const ENV_PREFIX = "OCULA_" as const;

/** Ocula-scoped env keys (without prefix). */
export const OCULA_ENV = {
  WORKDIR: "WORKDIR",
  CONTEXT_LIMIT: "CONTEXT_LIMIT",
  CONTEXT_EXACT: "CONTEXT_EXACT",
  COMPACT_KEEP_TURNS: "COMPACT_KEEP_TURNS",
  COMPACT_THRESHOLD: "COMPACT_THRESHOLD",
  COMPACT_AUTO: "COMPACT_AUTO",
  CODE_REPL_DEFAULT_RUNTIME: "CODE_REPL_DEFAULT_RUNTIME",
  CODE_REPL_TIMEOUT_MS: "CODE_REPL_TIMEOUT_MS",
  CODE_REPL_DISABLED: "CODE_REPL_DISABLED",
  PYTHON: "PYTHON",
  VENV: "VENV",
  DEEP_RESEARCH: "DEEP_RESEARCH",
  TAVILY_API_KEY: "TAVILY_API_KEY",
  THINKING: "THINKING",
  VERBOSE: "VERBOSE",
  HTTP: "HTTP",
} as const;

/** Provider / third-party env var names. */
export const PROVIDER_ENV = {
  DEEPSEEK_API_KEY: "DEEPSEEK_API_KEY",
  ANTHROPIC_API_KEY: "ANTHROPIC_API_KEY",
  ANTHROPIC_BASE_URL: "ANTHROPIC_BASE_URL",
  ANTHROPIC_AUTH_TOKEN: "ANTHROPIC_AUTH_TOKEN",
  MODEL_ID: "MODEL_ID",
  TAVILY_API_KEY: "TAVILY_API_KEY",
} as const;
