export {
  ErrorCode,
  type ErrorCode as ErrorCodeType,
  cliExitCodeFor,
  AppError,
  isAppError,
  type AppErrorOptions,
  validationError,
  configError,
  toolError,
  infraError,
  internalError,
  type ErrorRecord,
  toErrorRecord,
  errorRecordToEventPayload,
  isErrorRecord,
  toMessage,
  toStack,
  errorCodeOf,
  toolFailureMessage,
  toFailureOutcome,
  errorCodeFromToolOutcome,
  type ToolOutcomeForErrorCode,
} from "@moontide/shared/errors/index.js";
export { reportError, type ReportErrorOptions, type ReportErrorRoute } from "./report.js";
export { formatCliError, cliExitCode, formatCliErrorFromRecord } from "./cli.js";
