[package]
name = "desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
agent.workspace = true
agent-core.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
tempfile.workspace = true
wiremock = "0.6"
