[package]
name = "desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
agent.workspace = true
agent-core.workspace = true
anyhow.workspace = true
desktop-protocol = { path = "../desktop-protocol" }
tokio.workspace = true
tokio-util.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
wiremock = "0.6"
