export {
  executeTool,
  getToolDefinitions,
  registerDefaultTools,
  TOOL_PERMISSIONS,
  TOOL_CAPABILITIES,
  TOOL_NAMES,
  defineTool,
  defineTools,
  defineOptionalTool,
  resolveToolManifest,
  validateToolSpec,
  toolDefinitionToSpec,
  ToolRegistry,
  effectiveDecision,
  DEFAULT_TOOL_MANIFEST,
  BUILTIN_TOOL_MANIFEST,
  BUILTIN_PLUGIN_TOOL_MANIFEST,
  runGrep,
  normalizeGrepMaxResults,
  runHttpFetch,
  validateFetchUrl,
  normalizeMaxBytes,
  normalizeTimeoutMs,
  runBash,
  safePath,
  runRead,
  runWrite,
  runEdit,
  runGlob,
  runListDir,
  runGitDiff,
  runGitLog,
  runGitStatus,
  runGitSummaryLink,
  executeCodeRepl,
  defineCodeReplTools,
  runDeepResearch,
  defineDeepResearchTools,
  runWorkMem,
  defineWorkMemTools,
  resolveWorkingSetSnapshot,
} from "@moontide/tools";
export type {
  ToolSpec,
  ToolFactory,
  ToolManifestEntry,
  TrustPolicy,
  ToolRegistryPort,
  ToolName,
  PermissionDecision,
  ToolCapability,
  ToolPermissionRule,
  UserInteraction,
  ToolContext,
  ToolHandler,
  ToolDefinition,
  ResolvedWorkingSet,
  ResolveWorkingSetInput,
} from "@moontide/tools";
export {
  isAlwaysAllowEnabled,
  setAlwaysAllowOverride,
  resetAlwaysAllowOverride,
  describeAlwaysAllow,
} from "./always-allow-mode.js";
